# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source = /home/danny/.cache/wal/colors-hyprland.conf
#source = ~/.cache/wal/colors-hyprland.conf
$mainMod = SUPER
$terminal = ghostty
$fileManager = thunar
$menu = wofi --show drun --width 500 --height 420


bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu


#==========
# Move focus between windows
bind = SUPER, LEFT, movefocus, l
bind = SUPER, RIGHT, movefocus, r
bind = SUPER, UP, movefocus, u
bind = SUPER, DOWN, movefocus, d

# Move active window
bind = SUPER SHIFT, LEFT, movewindow, l
bind = SUPER SHIFT, RIGHT, movewindow, r
bind = SUPER SHIFT, UP, movewindow, u
bind = SUPER SHIFT, DOWN, movewindow, d

#=======Floating widget
bind = SUPER SHIFT, RIGHT, exec, sed -i 's/margin-right: .*/margin-right: 40px;/' ~/.config/ags/style.scss && pkill -9 ags && ags run --gtk 4 &
bind = SUPER SHIFT, LEFT, exec, sed -i 's/margin-right: .*/margin-right: 700px;/' ~/.config/ags/style.scss && pkill -9 ags && ags run --gtk 4 &


#===========

bind = SUPER, M, exec, ags toggle sidebar
bind = SUPER, SPACE, exec, wofi -show drun
bind = , PRINT, exec, grim -g "$(slurp)" ~/Pictures/screenshot.png
bind = SUPER, SPACE, exec, rofi -show drun




#volume
bind = ,XF86AudioRaiseVolume, exec, pamixer -i 5
bind = ,XF86AudioLowerVolume, exec, pamixer -d 5
bind = ,XF86AudioMute, exec, pamixer -t

bind = ,XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-


#wlogout

#bind = SUPER, ESCAPE, exec, wlogout
bind = SUPER, ESCAPE, exit



bind = SUPER, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy


exec-once = swaybg -i $(cat ~/.cache/wal/wal) -m fill
#exec-once = swaybg -i /home/danny/Pictures/wallpapers/Night-Moon.jpg -m fill
exec-once = wal -R
exec-once = hyprpaper
exec-once = ags run --gtk 4
exec-once = swaync
exec-once = hypridle
#exec-once = nwg-dock-hyprland
exec-once = waybar
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = blueman-applet
#exec-once = quickshell
exec-once = udiskie &

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


#===================2.Smooth animation

animations {
    enabled = yes

    bezier = smooth, 0.25, 0.1, 0.25, 1.0

    animation = windows, 1, 7, smooth
    animation = fade, 1, 7, smooth
    animation = workspaces, 1, 6, smooth
}


#===================3.Blur sidebar background

decoration {
    rounding = 15

    blur {
        enabled = true
        size = 8
        passes = 2
    }
}


#====================4. Floating rounded style

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
col.active_border = rgba(33ccffee) rgba(ff99c8ee) 45deg
col.inactive_border = rgba(595959aa)
}


#====================5. Workspace switch animation


bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5


#====================trackpad

input {
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        tap-to-click = true
        clickfinger_behavior = true
        drag_lock = true
    }
}



misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
